version: '3.8'

services:
  kong-api-gateway:
    image: kong:3.4.0
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    ports:
      - "8080:8000" # Kong Proxy
      - "8443:8443" # Kong Proxy (HTTPS)
    volumes:
      - ./kong_config/:/etc/kong/

  dota-db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: myRootPassword
      MYSQL_DATABASE: dota_db
    ports:
      - "3306:3306"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - zookeeper
  register-api:
    build:
      context: ./registerApi/
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # Spring Application Port
    depends_on:
      - kong-api-gateway
      - kafka
  dota-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Spring Application Port
    depends_on:
      - kong-api-gateway
      - dota-db
      - kafka
      - register-api